python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 2
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 4
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 6
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 8
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 10
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 12
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 14
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 16
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 18
python ./main.py --model-name ResNet18 --attack-loss cw --s-loss-name ce --batch-size 128  --sampler_iters 20

python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 2
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 4
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 6
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 8
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 10
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 12
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 14
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 16
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 18
python ./main.py --model-name ResNet18 --attack-loss ce --s-loss-name ce --batch-size 128  --sampler_iters 20
